
# Self-update
org.phoebus.applications.update/current_version=2026-01-07 23:59
org.phoebus.applications.update/update_url=https://controlssoftware.sns.ornl.gov/css_phoebus/nightly/phoebus-win.zip

# Data Browser のアーカイブURL
org.csstudio.trends.databrowser3/urls=jdbc:mysql://192.168.3.95:3306/archive|RDB
org.csstudio.trends.databrowser3/archives=jdbc:mysql://192.168.3.95:3306/archive|RDB

# RDB reader（読み出し用）
org.phoebus.archive.reader.rdb/user=report
org.phoebus.archive.reader.rdb/password=pass

# 既定アーカイブの扱い（推奨）
org.csstudio.trends.databrowser3/use_default_archives=true
org.csstudio.trends.databrowser3/drop_failed_archives=false
