<?xml version="1.0" encoding="UTF-8"?>
<databrowser>
  <title></title>
  <show_toolbar>true</show_toolbar>
  <update_period>3.0</update_period>
  <scroll_step>5</scroll_step>
  <scroll>true</scroll>
  <start>-6 minutes -6 seconds</start>
  <end>now</end>
  <archive_rescale>NONE</archive_rescale>
  <foreground>
    <red>0</red>
    <green>0</green>
    <blue>0</blue>
  </foreground>
  <background>
    <red>255</red>
    <green>255</green>
    <blue>255</blue>
  </background>
  <title_font>Liberation Sans|20|1</title_font>
  <label_font>Liberation Sans|14|1</label_font>
  <scale_font>Liberation Sans|12|0</scale_font>
  <legend_font>Liberation Sans|14|0</legend_font>
  <axes>
    <axis>
      <visible>true</visible>
      <name>Value 1</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>10966.0</min>
      <max>11658.0</max>
      <grid>false</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <visible>true</visible>
      <name>Value 2</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>-10.8</min>
      <max>3.6</max>
      <grid>false</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <visible>true</visible>
      <name>Value 3</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>-2350.0</min>
      <max>1250.0</max>
      <grid>false</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <visible>true</visible>
      <name>Value 4</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>-60.0</min>
      <max>156.0</max>
      <grid>false</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <visible>true</visible>
      <name>Value 5</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>382.0</min>
      <max>513.0</max>
      <grid>false</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
    <axis>
      <visible>true</visible>
      <name>Value 6</name>
      <use_axis_name>false</use_axis_name>
      <use_trace_names>true</use_trace_names>
      <right>false</right>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <min>-2.0</min>
      <max>114.0</max>
      <grid>false</grid>
      <autoscale>false</autoscale>
      <log_scale>false</log_scale>
    </axis>
  </axes>
  <annotations>
  </annotations>
  <pvlist>
    <pv>
      <display_name>RE:ch0:ARDUINO:LOOP_US</display_name>
      <visible>true</visible>
      <name>RE:ch0:ARDUINO:LOOP_US</name>
      <axis>0</axis>
      <color>
        <red>255</red>
        <green>0</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.1</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:ENC1:POSITION</display_name>
      <visible>true</visible>
      <name>RE:ch0:ENC1:POSITION</name>
      <axis>1</axis>
      <color>
        <red>0</red>
        <green>255</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:ENC2:POSITION</display_name>
      <visible>true</visible>
      <name>RE:ch0:ENC2:POSITION</name>
      <axis>1</axis>
      <color>
        <red>127</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>5000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:MTR1:POSITION</display_name>
      <visible>true</visible>
      <name>RE:ch0:MTR1:POSITION</name>
      <axis>2</axis>
      <color>
        <red>0</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:MTR1:SETPOINT</display_name>
      <visible>true</visible>
      <name>RE:ch0:MTR1:SETPOINT</name>
      <axis>2</axis>
      <color>
        <red>255</red>
        <green>127</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:MTR1:POSITION</display_name>
      <visible>true</visible>
      <name>RE:ch0:MTR2:POSITION</name>
      <axis>2</axis>
      <color>
        <red>127</red>
        <green>255</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>5000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:MTR1:RPM_SET</display_name>
      <visible>true</visible>
      <name>RE:ch0:MTR1:RPM_SET</name>
      <axis>3</axis>
      <color>
        <red>255</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:MTR2:RPM_SET</display_name>
      <visible>true</visible>
      <name>RE:ch0:MTR2:RPM_SET</name>
      <axis>3</axis>
      <color>
        <red>0</red>
        <green>127</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>5000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:ARDUINO:LIGHT_RAW</display_name>
      <visible>true</visible>
      <name>RE:ch0:ARDUINO:LIGHT_RAW</name>
      <axis>4</axis>
      <color>
        <red>255</red>
        <green>127</green>
        <blue>0</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>50000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
    <pv>
      <display_name>RE:ch0:ARDUINO:THERMISTOR</display_name>
      <visible>true</visible>
      <name>RE:ch0:ARDUINO:THERMISTOR</name>
      <axis>5</axis>
      <color>
        <red>127</red>
        <green>0</green>
        <blue>255</blue>
      </color>
      <trace_type>AREA</trace_type>
      <linewidth>2</linewidth>
      <line_style>SOLID</line_style>
      <point_type>NONE</point_type>
      <point_size>2</point_size>
      <waveform_index>0</waveform_index>
      <period>0.0</period>
      <ring_size>5000</ring_size>
      <request>OPTIMIZED</request>
      <archive>
        <name>RDB</name>
        <url>jdbc:mysql://192.168.3.102:3306/archive</url>
        <key>1</key>
      </archive>
    </pv>
  </pvlist>
</databrowser>
